version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: gulai-laravel
    restart: unless-stopped
    volumes:
      - ./gulai-russ-back:/var/www
    ports:
      - "8000:8000"
    depends_on:
      - postgres

  postgres:
    image: postgres:16
    container_name: gulai-postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: gulai
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    volumes:
      - pgdata:/var/lib/postgresql/data


volumes:
  pgdata:
